name: Apply Repository-Specific Issue Labels

on:
    workflow_call:
        inputs:
            issue_number:
                required: false
                type: number
            repository:
                required: true
                type: string
            pr_number:
                required: false
                type: number

permissions:
    issues: write
    pull-requests: write
    contents: read

jobs:
    extract-issue:
        if: inputs.issue_number == null && (github.base_ref != 'dev' && github.base_ref != 'staging' && github.base_ref != 'main')
        uses: ./.github/workflows/extract-issue-number.yml
        with:
            branch_name: ${{ github.head_ref || github.ref_name }}

    add-labels:
        needs: extract-issue
        runs-on: ubuntu-latest
        steps:
            - name: Apply custom labels to issue and PR
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  REPO_NAME="${{ inputs.repository }}"
                  ISSUE_NUMBER="${{ inputs.issue_number || needs.extract-issue.outputs.issue_number }}"
                  PR_NUMBER="${{ inputs.pr_number || github.event.pull_request.number }}"

                  echo "Debug information:"
                  echo "Repository: $REPO_NAME"
                  echo "Issue number: $ISSUE_NUMBER"
                  echo "PR number: $PR_NUMBER"

                  # Fail if no issue number is found
                  if [ -z "$ISSUE_NUMBER" ] || [ "$ISSUE_NUMBER" = "null" ]; then
                    echo "Error: No issue number found. Either provide an issue number as input or ensure the branch name contains one."
                    exit 1
                  fi

                  # Define repository-specific labels
                  case "$REPO_NAME" in
                    "Anthos-Capital/Affinity-Enrichment")
                      LABEL="Affinity Enrichment"
                      ;;
                    "Anthos-Capital/Alloy-ReactJS")
                      LABEL="Affinity Enrichment"
                      ;;
                    "Anthos-Capital/LinkedIn-Enrichment")
                      LABEL="LinkedIn Enrichment"
                      ;;
                    "Anthos-Capital/Alloy-ReactJS")
                      LABEL="Alloy"
                      ;;
                    "Anthos-Capital/Alloy-WebServices")
                      LABEL="Alloy"
                      ;;
                    "Anthos-Capital/Company-Name-resolver")
                      LABEL="CNR"
                      ;;
                    "Anthos-Capital/Company-Name-Resolver-FE")
                      LABEL="CNR"
                      ;;
                    "Anthos-Capital/company-categorization")
                      LABEL="Company Categorization"
                      ;;
                    "Anthos-Capital/company-filter")
                      LABEL="Company Filter"
                      ;;
                    "Anthos-Capital/company-snapshot")
                      LABEL="Company Snapshot"
                      ;;
                    "Anthos-Capital/Facesheets")
                      LABEL="Facesheets"
                      ;;
                    "Anthos-Capital/Forge-FE")
                      LABEL="Forge"
                      ;;
                    "Anthos-Capital/Forge-BE")
                      LABEL="Forge"
                      ;;
                    "Anthos-Capital/foundry")
                      LABEL="Foundry"
                      ;;
                    "Anthos-Capital/Glean-Indexer")
                      LABEL="Glean Indexer"
                      ;;
                    "Anthos-Capital/Kafka")
                      LABEL="Kafka"
                      ;;
                    "Anthos-Capital/LinkedIn-Enrichment")
                      LABEL="LinkedIn Enrichment"
                      ;;
                    "Anthos-Capital/Mosaic-Quench-BE")
                      LABEL="Quench"
                      ;;
                    "Anthos-Capital/Mosaic-Quench-FE")
                      LABEL="Quench"
                      ;;
                    *)
                      LABEL=""
                      ;;
                  esac

                  if [ -n "$LABEL" ]; then
                    echo "Attempting to apply label: $LABEL"
                    
                    # Apply label to issue
                    curl -X POST \
                      -H "Authorization: token $GITHUB_TOKEN" \
                      -H "Accept: application/vnd.github.v3+json" \
                      "https://api.github.com/repos/$REPO_NAME/issues/$ISSUE_NUMBER/labels" \
                      -d "{\"labels\":[\"$LABEL\"]}"
                    
                    # Apply label to PR if PR number exists
                    if [ -n "$PR_NUMBER" ] && [ "$PR_NUMBER" != "null" ]; then
                      curl -X POST \
                        -H "Authorization: token $GITHUB_TOKEN" \
                        -H "Accept: application/vnd.github.v3+json" \
                        "https://api.github.com/repos/$REPO_NAME/issues/$PR_NUMBER/labels" \
                        -d "{\"labels\":[\"$LABEL\"]}"
                      echo "Label applied to PR #$PR_NUMBER"
                    fi
                    
                    echo "Label application completed"
                  else
                    echo "No specific label defined for this repository"
                  fi
