name: Apply Repository-Specific Issue Labels
on:
    issues:
        types: [opened]

jobs:
    add-label:
        runs-on: ubuntu-latest
        steps:
            - name: Authenticate GitHub CLI
              run: |
                  echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

            - name: Apply custom label based on the repository
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  REPO_NAME="${{ github.repository }}"
                  echo "Processing issue for repository: $REPO_NAME"

                  # Define repository-specific labels
                  case "$REPO_NAME" in
                    "Anthos-Capital/Mosaic-Quench-FE")
                      LABEL="Quench"
                      ;;
                    "Anthos-Capital/LinkedIn-Enrichment")
                      LABEL="LinkedIn Enrichment"
                      ;;
                    *)
                      LABEL=""
                      ;;
                  esac

                  if [ -n "$LABEL" ]; then
                    echo "Applying label: $LABEL"
                    gh issue edit ${{ github.event.issue.number }} --add-label "$LABEL" --repo "$REPO_NAME"
                  else
                    echo "No specific label defined for this repository"
                  fi
