name: Apply Repository-Specific Issue Labels
on:
    issues:
        types: [opened]

# Add explicit permissions
permissions:
    issues: write
    contents: read

jobs:
    add-label:
        runs-on: ubuntu-latest
        steps:
            - name: Apply custom label based on the repository
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  REPO_NAME="${{ github.repository }}"
                  ISSUE_NUMBER="${{ github.event.issue.number }}"

                  echo "Debug information:"
                  echo "Repository: $REPO_NAME"
                  echo "Issue number: $ISSUE_NUMBER"

                  # Define repository-specific labels
                  case "$REPO_NAME" in
                    "Anthos-Capital/Mosaic-Quench-FE")
                      LABEL="Quench"
                      ;;
                    "Anthos-Capital/LinkedIn-Enrichment")
                      LABEL="LinkedIn Enrichment"
                      ;;
                    *)
                      LABEL=""
                      ;;
                  esac

                  if [ -n "$LABEL" ]; then
                    echo "Attempting to apply label: $LABEL"
                    # Use GitHub REST API directly instead of gh CLI
                    curl -X POST \
                      -H "Authorization: token $GITHUB_TOKEN" \
                      -H "Accept: application/vnd.github.v3+json" \
                      "https://api.github.com/repos/$REPO_NAME/issues/$ISSUE_NUMBER/labels" \
                      -d "{\"labels\":[\"$LABEL\"]}"
                    
                    echo "Label application attempt completed"
                  else
                    echo "No specific label defined for this repository"
                  fi
