name: Apply Repository-Specific Issue Labels

on:
    workflow_call:
        inputs:
            issue_number:
                required: true
                type: number
            repository:
                required: true
                type: string
        secrets:
            WORKFLOW_TOKEN:
                required: true

permissions:
    issues: write
    contents: read

jobs:
    add-label:
        runs-on: ubuntu-latest
        steps:
            - name: Apply custom label based on the repository
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  REPO_NAME="${{ inputs.repository }}"
                  ISSUE_NUMBER="${{ inputs.issue_number }}"

                  echo "Debug information:"
                  echo "Repository: $REPO_NAME"
                  echo "Issue number: $ISSUE_NUMBER"

                  # Define repository-specific labels
                  case "$REPO_NAME" in
                    "Anthos-Capital/Affinity-Enrichment")
                      LABEL="Affinity Enrichment"
                      ;;
                    "Anthos-Capital/Alloy-ReactJS")
                      LABEL="Affinity Enrichment"
                      ;;
                    "Anthos-Capital/LinkedIn-Enrichment")
                      LABEL="LinkedIn Enrichment"
                      ;;
                    "Anthos-Capital/Alloy-ReactJS")
                      LABEL="Alloy"
                      ;;
                    "Anthos-Capital/Alloy-WebServices")
                      LABEL="Alloy"
                      ;;
                    "Anthos-Capital/Company-Name-resolver")
                      LABEL="CNR"
                      ;;
                    "Anthos-Capital/Company-Name-Resolver-FE")
                      LABEL="CNR"
                      ;;
                    "Anthos-Capital/company-categorization")
                      LABEL="Company Categorization"
                      ;;
                    "Anthos-Capital/company-filter")
                      LABEL="Company Filter"
                      ;;
                    "Anthos-Capital/company-snapshot")
                      LABEL="Company Snapshot"
                      ;;
                    "Anthos-Capital/Facesheets")
                      LABEL="Facesheets"
                      ;;
                    "Anthos-Capital/Forge-FE")
                      LABEL="Forge"
                      ;;
                    "Anthos-Capital/Forge-BE")
                      LABEL="Forge"
                      ;;
                    "Anthos-Capital/foundry")
                      LABEL="Foundry"
                      ;;
                    "Anthos-Capital/Glean-Indexer")
                      LABEL="Glean Indexer"
                      ;;
                    "Anthos-Capital/Kafka")
                      LABEL="Kafka"
                      ;;
                    "Anthos-Capital/LinkedIn-Enrichment")
                      LABEL="LinkedIn Enrichment"
                      ;;
                    "Anthos-Capital/Mosaic-Quench-BE")
                      LABEL="Quench"
                      ;;
                    "Anthos-Capital/Mosaic-Quench-FE")
                      LABEL="Quench"
                      ;;
                    *)
                      LABEL=""
                      ;;
                  esac

                  if [ -n "$LABEL" ]; then
                    echo "Attempting to apply label: $LABEL"
                    curl -X POST \
                      -H "Authorization: token $GITHUB_TOKEN" \
                      -H "Accept: application/vnd.github.v3+json" \
                      "https://api.github.com/repos/$REPO_NAME/issues/$ISSUE_NUMBER/labels" \
                      -d "{\"labels\":[\"$LABEL\"]}"
                    
                    echo "Label application attempt completed"
                  else
                    echo "No specific label defined for this repository"
                  fi
