name: Auto-Assign PR to Author

on:
    pull_request:
        types: [opened]

jobs:
    assing_author:
        name: Assign author to PR
        runs-on: ubuntu-latest
        steps:
            - name: Assign author to PR
              uses: technote-space/assign-author@v1
