name: Check PR Linked Issues

on:
    pull_request:
        types: [opened, edited, reopened, synchronize]
    workflow_call: {}

jobs:
    check_pull_requests:
        if: (github.head_ref != 'dev' && github.head_ref != 'staging') || github.base_ref != 'main'
        runs-on: ubuntu-latest
        name: Check linked issues
        permissions:
            issues: read
            pull-requests: write
            actions: read
        steps:
            - uses: nearform-actions/github-action-check-linked-issues@v1
              id: check-linked-issues
              with:
                  exclude-branches: "release/**, dependabot/**"
            # OPTIONAL: Use the output from the `check-linked-issues` step
            - name: Get the output
              run: echo "How many linked issues? ${{ steps.check-linked-issues.outputs.linked_issues_count }}"
