name: Move Zenhub Issues on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  move_issues:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check Associated Issues
        id: extract_issues
        run: |
          echo "Searching for issues..."
          # Extract issues from PR description using regex
          ISSUES=$(echo "${{ github.event.pull_request.body }}" | grep -o '#[0-9]\+')
          echo "::set-output name=issues::${ISSUES}"
          done
