name: "[Zenhub] Move Multiple Issues to Done"

on:
    pull_request:
        types: [closed]
        branches:
            - main
    workflow_call: {}

jobs:
    process_issues:
        if: github.event.pull_request.merged == true && github.base_ref == 'main'
        runs-on: ubuntu-latest
        steps:
            - name: Get Linked Issues
              id: get-issues
              shell: bash
              run: |
                  # Temporarily return empty array for testing
                  echo "issues=[]" >> "$GITHUB_OUTPUT"
                  echo "Test mode - skipping issue processing"

            # Commenting out the actual move step for now
            # - name: Move Issues in Zenhub
            #   if: steps.get-issues.outputs.issues != '[]'
            #   run: |
            #       TARGET_PIPELINE_ID="Z2lkOi8vcmFwdG9yL1BpcGVsaW5lLzM0MDQ5Njg"
            #       ISSUES=$(echo '${{ steps.get-issues.outputs.issues }}' | jq -r '.[]')
            #       ...
